export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const INIT_USER = 'INIT_USER'
export const SET_SESSIONKEY = 'SET_SESSIONKEY'
export const USER_CARS = 'USER_CARS'
export const CAR_INFO = 'CAR_INFO'
